import { compareStrings } from '../order.ts'
import { identityKey } from '../spec-tree/index.ts'
import type { ScenarioIdentity } from '../spec-tree/index.ts'
import type { CapabilitySpec, RequirementSpec } from '../spec-file/index.ts'
import type { ProofSite } from '../test-scan/index.ts'
import { firstSiteByIdentity } from './locate.ts'

/**
 * Renders the tree as the readable site a person reads — the delivery view of the
 * storage/delivery split (`docs/design.md` §4). The committed files hold only titles and
 * locations; this joins them back to the tests, so each requirement shows its description
 * (from the file) and each scenario its Gherkin and current position (from the test).
 *
 * One page per capability plus an index, plus a code page per test file: a scenario's whole
 * point is that its proof is readable, so the site carries the proof too. Each test's page
 * holds one anchored snippet per proof, and every scenario links to the snippet that proves
 * it. The Gherkin and the code are delivered, never stored, so this is not a second copy of
 * behavior.
 */

const GENERATED = '<!-- generated by `proofspec render`; do not edit. The tests are the source of truth. -->'
const INTRO = '_The living spec: every capability, its requirements, and the scenarios that prove them — pulled live from the tests._'
const UNPROVEN = '_Unproven — no test currently proves this scenario._'

/** One rendered file: its path within the output directory, and its Markdown. */
export type RenderedPage = {
  readonly path: string
  readonly content: string
}

/** A test file to render as a code page: its path and its whole source. */
export type TestSource = {
  readonly path: string
  readonly source: string
}

export function renderSite(
  specs: readonly CapabilitySpec[],
  sites: readonly ProofSite[],
  tests: readonly TestSource[],
): readonly RenderedPage[] {
  // The proof sites are joined by the same collision rule locate uses, so the position the
  // site shows is the one the rest of the tool agrees on.
  const proven = firstSiteByIdentity(sites)
  // Name order here and nowhere else in the render: the file order the specs were read in
  // must not change the site, but the requirement and scenario order is spec-file's, kept as
  // given so the ordering rule stays in one place.
  const capabilities = [...specs].sort((a, b) => compareStrings(a.capability, b.capability))

  const index: RenderedPage = { path: 'index.md', content: renderIndex(capabilities) }
  const capabilityPages = capabilities.map(capability => ({
    path: `${capability.capability}.md`,
    content: renderCapabilityPage(capability, proven),
  }))
  return [index, ...capabilityPages, ...renderCodePages(sites, tests)]
}

function renderIndex(capabilities: readonly CapabilitySpec[]): string {
  const nav =
    capabilities.length === 0
      ? '_No capabilities yet._'
      : ['**Capabilities**', capabilities.map(one => `- [${one.capability}](${one.capability}.md)`).join('\n')].join('\n\n')
  return `${[frontmatter('ProofSpec — living spec'), GENERATED, INTRO, nav].join('\n\n')}\n`
}

function renderCapabilityPage(capability: CapabilitySpec, proven: ProvenSites): string {
  const requirements = capability.requirements.map(requirement =>
    renderRequirement(capability.capability, requirement, proven),
  )
  return `${[frontmatter(capability.capability), GENERATED, ...requirements].join('\n\n')}\n`
}

function renderRequirement(capability: string, requirement: RequirementSpec, proven: ProvenSites): string {
  const scenarios = requirement.scenarios.map(scenario =>
    renderScenario({ capability, requirement: requirement.requirement, scenario: scenario.scenario }, proven),
  )
  return [`## Requirement: ${requirement.requirement}`, requirement.description, ...scenarios].join('\n\n')
}

function renderScenario(identity: ScenarioIdentity, proven: ProvenSites): string {
  const heading = `### Scenario: ${identity.scenario}`
  const site = proven.get(identityKey(identity))
  if (site === undefined) {
    // Recorded but no test proves it: the spec has drifted. Show it rather than drop it, so
    // the reader sees the gap instead of a page that silently omits a promise.
    return [heading, UNPROVEN].join('\n\n')
  }
  // The location links to the anchored snippet that proves this scenario. The fragment is the
  // slug of the scenario title — the same one the code page's heading gets — so the anchor
  // reads as the scenario, not a bare line number, and the reader lands on the proof.
  const location = `[${site.file}:${site.line}](${site.file}#${slugOf(site.scenario)})`
  if (site.steps.length === 0) return [heading, location].join('\n\n')
  const steps = site.steps.map(step => `- **${step.keyword}** ${step.text}`).join('\n')
  return [heading, location, steps].join('\n\n')
}

// --- code pages --------------------------------------------------------------

function renderCodePages(sites: readonly ProofSite[], tests: readonly TestSource[]): readonly RenderedPage[] {
  const byFile = sitesByFile(sites)
  return [...tests]
    .filter(test => byFile.has(test.path))
    .sort((a, b) => compareStrings(a.path, b.path))
    .map(test => ({ path: `${test.path}.md`, content: renderCodePage(test, byFile.get(test.path)!) }))
}

function renderCodePage(test: TestSource, fileSites: readonly ProofSite[]): string {
  const lines = test.source.split('\n')
  const snippets = [...fileSites].sort((a, b) => a.line - b.line).map(site => renderSnippet(site, lines))
  return `${[frontmatter(test.path), GENERATED, ...snippets].join('\n\n')}\n`
}

function renderSnippet(site: ProofSite, lines: readonly string[]): string {
  // The scenario title is the heading, so its anchor reads as the scenario a reader clicked.
  // Then the Gherkin, then the proving lines: the claim sits right above its proof, so a reader
  // can judge whether the test does what the claim says — the whole reason to co-locate them.
  const snippet = lines.slice(site.line - 1, site.endLine).join('\n')
  const fence = ['```ts', snippet, '```'].join('\n')
  const parts = [`## ${site.scenario}`, `\`${site.file}:${site.line}\``]
  if (site.steps.length > 0) parts.push(site.steps.map(step => `- **${step.keyword}** ${step.text}`).join('\n'))
  parts.push(fence)
  return parts.join('\n\n')
}

/**
 * The heading slug Quartz gives a title, so a scenario's link can target its snippet. Matches
 * github-slugger for the plain-English titles the tests carry: lower-case, drop punctuation,
 * spaces to hyphens. Titles are unique within a requirement, so the slug is a stable anchor.
 */
function slugOf(title: string): string {
  return title.toLowerCase().replace(/[^\w\- ]+/g, '').replace(/ /g, '-')
}

/** The proof sites in each test file, so its code page can show one snippet per proof. */
function sitesByFile(sites: readonly ProofSite[]): ReadonlyMap<string, readonly ProofSite[]> {
  const byFile = new Map<string, ProofSite[]>()
  for (const site of sites) {
    const held = byFile.get(site.file) ?? []
    held.push(site)
    byFile.set(site.file, held)
  }
  return byFile
}

/** A YAML frontmatter block naming the page, so a static-site renderer titles it. */
function frontmatter(title: string): string {
  return `---\ntitle: ${title}\n---`
}

/** Each recorded scenario's proof site, or absent when no test proves it. */
type ProvenSites = ReadonlyMap<string, ProofSite>
